name: "Automated tests"

on: pull_request

jobs:
  jest:
    name: jest ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: "lts/hydrogen"

      - run: npm ci
      - run: npm test
